import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

// Generate Skill Gap Analysis Report PDF
export const generateSkillGapReport = (studentName, gapData, skillProfile) => {
  const doc = new jsPDF();
  const primaryColor = [45, 106, 79]; // #2D6A4F
  const orangeColor = [231, 111, 81]; // #E76F51

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('AYUSH-SETU', 15, 15);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Skill Gap Analysis Report', 15, 25);
  doc.text(`Student: ${studentName}`, 120, 15);
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 120, 25);

  // Overall Readiness Score
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Readiness Score', 15, 50);
  const score = gapData?.readinessScore || 0;
  doc.setFontSize(36);
  doc.setTextColor(...primaryColor);
  doc.text(`${score}%`, 15, 70);
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(score >= 70 ? 'INDUSTRY READY' : 'NEEDS IMPROVEMENT', 55, 65);
  
  // Skill Scores Table
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Skill Category Breakdown', 15, 90);

  const categories = skillProfile?.categories || [];
  const tableData = categories.map(c => [
    c.name,
    `${c.percentage || 0}%`,
    '70%',
    c.percentage >= 70 ? '✓ Met' : '✗ Gap',
  ]);

  doc.autoTable({
    startY: 95,
    head: [['Skill Category', 'Your Score', 'Benchmark', 'Status']],
    body: tableData.length > 0 ? tableData : [['No assessments taken yet', '-', '70%', '-']],
    headStyles: { fillColor: primaryColor, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 250, 247] },
    styles: { fontSize: 10 },
  });

  // Gap Analysis
  const gaps = gapData?.gaps || [];
  const yAfterTable = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Identified Gaps & Recommendations', 15, yAfterTable);

  if (gaps.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text('No skill gaps identified. Complete assessments to get personalized recommendations.', 15, yAfterTable + 10);
  } else {
    gaps.forEach((gap, i) => {
      const y = yAfterTable + 15 + (i * 25);
      if (y > 260) return;
      doc.setFillColor(gap.severity === 'high' ? 254 : gap.severity === 'medium' ? 254 : 240, 
                       gap.severity === 'high' ? 226 : gap.severity === 'medium' ? 243 : 253, 
                       gap.severity === 'high' ? 226 : gap.severity === 'medium' ? 200 : 244);
      doc.rect(14, y - 5, 182, 20, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(0,0,0);
      doc.text(`${gap.category}: ${gap.studentScore}% (Gap: ${gap.gap}%)`, 18, y + 2);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text(`→ ${gap.recommendation}`, 18, y + 10);
    });
  }

  // Footer
  doc.setFillColor(...primaryColor);
  doc.rect(0, 282, 210, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text('Generated by AYUSH-SETU | PS ID 26044 | Team Tenet | Smart India Hackathon 2026', 15, 291);

  doc.save(`AYUSH-SETU_Skill_Gap_Report_${studentName.replace(' ', '_')}.pdf`);
};

// Generate AYUSH Resume PDF
export const generateAyushResume = (resumeData) => {
  const doc = new jsPDF();
  const primaryColor = [45, 106, 79];
  const { user, profile, skills, certificates, projects, applications } = resumeData || {};

  // Sidebar
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 65, 297, 'F');

  // Name & Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(user?.name || 'Student Name', 10, 20, { maxWidth: 50 });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(profile?.specialization || 'AYUSH Practitioner', 10, 35, { maxWidth: 50 });

  // Contact
  doc.setFontSize(9);
  doc.text('CONTACT', 10, 55);
  doc.setDrawColor(255, 255, 255);
  doc.line(10, 57, 55, 57);
  doc.text(user?.email || '', 10, 65, { maxWidth: 50 });
  doc.text(user?.phone || '', 10, 73, { maxWidth: 50 });

  // Skills sidebar
  doc.text('SKILLS', 10, 90);
  doc.line(10, 92, 55, 92);
  (skills || []).slice(0, 6).forEach((s, i) => {
    doc.text(`${s.name || s.category}: ${s.percentage || 0}%`, 10, 100 + i * 10, { maxWidth: 50 });
    doc.setFillColor(255, 255, 255, 0.3);
    doc.setDrawColor(255,255,255);
    doc.roundedRect(10, 102 + i*10, 45, 3, 1, 1);
    doc.setFillColor(231, 111, 81);
    doc.roundedRect(10, 102 + i*10, Math.min((s.percentage || 0) * 0.45, 45), 3, 1, 1, 'F');
  });

  // Main content
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('PROFILE', 75, 20);
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(75, 22, 195, 22);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(profile?.bio || 'AYUSH practitioner with a passion for holistic healthcare.', 75, 30, { maxWidth: 120 });

  // Education
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('EDUCATION', 75, 55);
  doc.line(75, 57, 195, 57);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(profile?.institution || 'AYUSH Institution', 75, 65);
  doc.setTextColor(100,100,100);
  doc.text(`Enrolled: ${profile?.enrollmentYear || new Date().getFullYear()}`, 75, 73);
  doc.setTextColor(0,0,0);

  // Certificates
  if ((certificates || []).length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('CERTIFICATIONS', 75, 90);
    doc.line(75, 92, 195, 92);
    certificates.slice(0, 4).forEach((c, i) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text(c.title, 75, 100 + i * 18);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100,100,100);
      doc.text(`${c.issuer} | ${new Date(c.issueDate).toLocaleDateString('en-IN')}`, 75, 107 + i * 18);
      doc.setTextColor(0,0,0);
    });
  }

  // Projects
  const projY = 100 + Math.min((certificates||[]).length, 4) * 18 + 15;
  if ((projects || []).length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text('PROJECTS', 75, projY);
    doc.line(75, projY + 2, 195, projY + 2);
    projects.slice(0, 3).forEach((p, i) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text(p.title, 75, projY + 10 + i * 20);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text(p.description || '', 75, projY + 17 + i * 20, { maxWidth: 120 });
    });
  }

  // Footer
  doc.setFillColor(...primaryColor);
  doc.rect(0, 282, 210, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text('Generated by AYUSH-SETU Platform | SIH 2026 | Team Tenet', 75, 291);

  doc.save(`AYUSH_Resume_${(user?.name || 'Student').replace(' ', '_')}.pdf`);
};
